add healthcheck code to actions

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -26,7 +26,24 @@ jobs:
       - name: Docker build
         run: docker build . -t intdocker -f docker/Dockerfile.mcservertest
       - name: Docker run
-        run: docker run -d -p 25565:25565 -p 25575:25575 --name intdockertest intdocker
+        run: |
+          docker run -d -p 25565:25565 -p 25575:25575 --name intdockertest intdocker
+
+          status="false"
+          for i in {1..10}; do
+            docker inspect intdocker > /dev/null 2>& 1 && status="true"
+            if [[ $status == "true" ]]; then
+              break
+            fi
+
+            echo "$i: Waiting for container response..."
+            sleep 1
+          done
+
+          if [[ $status == "false" ]]; then
+            echo "Failed to start Docker container"
+            exit 1
+          fi
       - name: Go test
         run: go test ./... -count=1
   artifact-release:
